# Generated by Django 5.2.8 on 2025-12-11 13:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('owner', 'name')},
        ),
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
    ]
